### ISSUE TITLE
New Scoreboard

### ISSUE THREAD

**Issue by Boo1236** [andrewmaxwell/mortal-wombat#19]
Your score can be affected by:
- Collectibles (jewels, rubies, etc...; also you can customize how much it affects your score in the block config)
- How quickly you finish the level
- If you do what the NPC's tell you to
- How much damage you take???
I'll think of more later

**Comment by andrewmaxwell** [comment]
Since this is highly dependent on the level, this would probably best be implemented through tile logic. If you make the level and tell me what the NPCs should do/say, I can write the tile logic.
